<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE articles [<!ELEMENT articles ANY><!ELEMENT article ANY><!ATTLIST article id ID #REQUIRED>]>
<articles folder="c:\content" type="Howto" version="16.1" docsdir="concepts">
  <article name="UI Widgets" sort="10 UI Widgets" id="UI Widgets">
    <article name="Basics" sort="0 Basics" id="UI Widgets/Basics">
      <article name="Installation" sort="01 Installation" id="UI Widgets/Basics/Installation" root="true" file="c:\content\10 UI Widgets\0 Basics\01 Installation\Installation.md">
        <article name="Local Scripts" sort="01 Local Scripts" id="UI Widgets/Basics/Installation/Local Scripts" file="c:\content\10 UI Widgets\0 Basics\01 Installation\01 Local Scripts.md" />
        <article name="CDN Services" sort="05 CDN Services" id="UI Widgets/Basics/Installation/CDN Services" file="c:\content\10 UI Widgets\0 Basics\01 Installation\05 CDN Services.md" />
        <article name="NuGet Package" sort="10 NuGet Package" id="UI Widgets/Basics/Installation/NuGet Package" file="c:\content\10 UI Widgets\0 Basics\01 Installation\10 NuGet Package.md" />
        <article name="Bower Package" sort="15 Bower Package" id="UI Widgets/Basics/Installation/Bower Package" file="c:\content\10 UI Widgets\0 Basics\01 Installation\15 Bower Package.md" />
        <article name="npm Package" sort="20 npm Package" id="UI Widgets/Basics/Installation/npm Package" file="c:\content\10 UI Widgets\0 Basics\01 Installation\20 npm Package.md" />
      </article>
      <article name="Add Themes" sort="05 Add Themes" id="UI Widgets/Basics/Add Themes" root="true" file="c:\content\10 UI Widgets\0 Basics\05 Add Themes\Add Themes.md">
        <article name="Use Local Themes" sort="0 Use Local Themes" id="UI Widgets/Basics/Add Themes/Use Local Themes" file="c:\content\10 UI Widgets\0 Basics\05 Add Themes\0 Use Local Themes.md" />
        <article name="Use a CDN" sort="1 Use a CDN" id="UI Widgets/Basics/Add Themes/Use a CDN" file="c:\content\10 UI Widgets\0 Basics\05 Add Themes\1 Use a CDN.md" />
      </article>
      <article name="Widget Basics - jQuery" sort="10 Widget Basics - jQuery" id="UI Widgets/Basics/Widget Basics - jQuery" root="true" file="c:\content\10 UI Widgets\0 Basics\10 Widget Basics - jQuery\Widget Basics - jQuery.md">
        <article name="Create and Configure a Widget" sort="01 Create and Configure a Widget" id="UI Widgets/Basics/Widget Basics - jQuery/Create and Configure a Widget" file="c:\content\10 UI Widgets\0 Basics\10 Widget Basics - jQuery\01 Create and Configure a Widget.md" />
        <article name="Get and Set Options" sort="05 Get and Set Options" id="UI Widgets/Basics/Widget Basics - jQuery/Get and Set Options" file="c:\content\10 UI Widgets\0 Basics\10 Widget Basics - jQuery\05 Get and Set Options.md" />
        <article name="Call Methods" sort="10 Call Methods" id="UI Widgets/Basics/Widget Basics - jQuery/Call Methods" file="c:\content\10 UI Widgets\0 Basics\10 Widget Basics - jQuery\10 Call Methods.md" />
        <article name="Handle Events" sort="15 Handle Events" id="UI Widgets/Basics/Widget Basics - jQuery/Handle Events" file="c:\content\10 UI Widgets\0 Basics\10 Widget Basics - jQuery\15 Handle Events.md" />
        <article name="Destroy a Widget" sort="20 Destroy a Widget" id="UI Widgets/Basics/Widget Basics - jQuery/Destroy a Widget" file="c:\content\10 UI Widgets\0 Basics\10 Widget Basics - jQuery\20 Destroy a Widget.md" />
      </article>
      <article name="Widget Basics - AngularJS" sort="20 Widget Basics - AngularJS" id="UI Widgets/Basics/Widget Basics - AngularJS" root="true" file="c:\content\10 UI Widgets\0 Basics\20 Widget Basics - AngularJS\Widget Basics - AngularJS.md">
        <article name="Create and Configure a Widget" sort="01 Create and Configure a Widget" id="UI Widgets/Basics/Widget Basics - AngularJS/Create and Configure a Widget" file="c:\content\10 UI Widgets\0 Basics\20 Widget Basics - AngularJS\01 Create and Configure a Widget.md" />
        <article name="Change Options" sort="05 Change Options" id="UI Widgets/Basics/Widget Basics - AngularJS/Change Options" file="c:\content\10 UI Widgets\0 Basics\20 Widget Basics - AngularJS\05 Change Options.md" />
        <article name="Call Methods" sort="10 Call Methods" id="UI Widgets/Basics/Widget Basics - AngularJS/Call Methods" file="c:\content\10 UI Widgets\0 Basics\20 Widget Basics - AngularJS\10 Call Methods.md" />
        <article name="Handle Events" sort="15 Handle Events" id="UI Widgets/Basics/Widget Basics - AngularJS/Handle Events" file="c:\content\10 UI Widgets\0 Basics\20 Widget Basics - AngularJS\15 Handle Events.md" />
        <article name="Destroy a Widget" sort="20 Destroy a Widget" id="UI Widgets/Basics/Widget Basics - AngularJS/Destroy a Widget" file="c:\content\10 UI Widgets\0 Basics\20 Widget Basics - AngularJS\20 Destroy a Widget.md" />
      </article>
      <article name="Widget Basics - Knockout" sort="25 Widget Basics - Knockout" id="UI Widgets/Basics/Widget Basics - Knockout" root="true" file="c:\content\10 UI Widgets\0 Basics\25 Widget Basics - Knockout\Widget Basics - Knockout.md">
        <article name="Create and Configure a Widget" sort="01 Create and Configure a Widget" id="UI Widgets/Basics/Widget Basics - Knockout/Create and Configure a Widget" file="c:\content\10 UI Widgets\0 Basics\25 Widget Basics - Knockout\01 Create and Configure a Widget.md" />
        <article name="Change Options" sort="05 Change Options" id="UI Widgets/Basics/Widget Basics - Knockout/Change Options" file="c:\content\10 UI Widgets\0 Basics\25 Widget Basics - Knockout\05 Change Options.md" />
        <article name="Call Methods" sort="10 Call Methods" id="UI Widgets/Basics/Widget Basics - Knockout/Call Methods" file="c:\content\10 UI Widgets\0 Basics\25 Widget Basics - Knockout\10 Call Methods.md" />
        <article name="Handle Events" sort="15 Handle Events" id="UI Widgets/Basics/Widget Basics - Knockout/Handle Events" file="c:\content\10 UI Widgets\0 Basics\25 Widget Basics - Knockout\15 Handle Events.md" />
        <article name="Destroy a Widget" sort="20 Destroy a Widget" id="UI Widgets/Basics/Widget Basics - Knockout/Destroy a Widget" file="c:\content\10 UI Widgets\0 Basics\25 Widget Basics - Knockout\20 Destroy a Widget.md" />
      </article>
      <article name="Application Templates" sort="30 Application Templates" id="UI Widgets/Basics/Application Templates" root="true" file="c:\content\10 UI Widgets\0 Basics\30 Application Templates\Application Templates.md">
        <article name="Web Application" sort="0 Web Application" id="UI Widgets/Basics/Application Templates/Web Application" file="c:\content\10 UI Widgets\0 Basics\30 Application Templates\0 Web Application.md" />
        <article name="Mobile Application" sort="1 Mobile Application" id="UI Widgets/Basics/Application Templates/Mobile Application" file="c:\content\10 UI Widgets\0 Basics\30 Application Templates\1 Mobile Application\Mobile Application.md">
          <article name="Knockout Approach" sort="1 Knockout Approach" id="UI Widgets/Basics/Application Templates/Mobile Application/Knockout Approach" file="c:\content\10 UI Widgets\0 Basics\30 Application Templates\1 Mobile Application\1 Knockout Approach.md" />
          <article name="Angular Approach" sort="2 Angular Approach" id="UI Widgets/Basics/Application Templates/Mobile Application/Angular Approach" file="c:\content\10 UI Widgets\0 Basics\30 Application Templates\1 Mobile Application\2 Angular Approach.md" />
        </article>
      </article>
      <article name="TypeScript Support" sort="40 TypeScript Support" id="UI Widgets/Basics/TypeScript Support" root="true" file="c:\content\10 UI Widgets\0 Basics\40 TypeScript Support\TypeScript Support.md">
        <article name="Reference TypeScript Definitions" sort="01 Reference TypeScript Definitions" id="UI Widgets/Basics/TypeScript Support/Reference TypeScript Definitions" file="c:\content\10 UI Widgets\0 Basics\40 TypeScript Support\01 Reference TypeScript Definitions.md" />
        <article name="Configure a Widget" sort="05 Configure a Widget" id="UI Widgets/Basics/TypeScript Support/Configure a Widget" file="c:\content\10 UI Widgets\0 Basics\40 TypeScript Support\05 Configure a Widget.md" />
        <article name="Access a Widget" sort="10 Access a Widget" id="UI Widgets/Basics/TypeScript Support/Access a Widget" file="c:\content\10 UI Widgets\0 Basics\40 TypeScript Support\10 Access a Widget.md" />
      </article>
    </article>
    <article name="UI Widget Categories" sort="10 UI Widget Categories" id="UI Widgets/UI Widget Categories">
      <article name="Collection Container Widgets" sort="10 Collection Container Widgets" id="UI Widgets/UI Widget Categories/Collection Container Widgets" root="true" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\Collection Container Widgets.md">
        <article name="Common Tasks" sort="0 Common Tasks" id="UI Widgets/UI Widget Categories/Collection Container Widgets/Common Tasks" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\0 Common Tasks\Common Tasks.md">
          <article name="Specify Data Source" sort="0 Specify Data Source" id="UI Widgets/UI Widget Categories/Collection Container Widgets/Common Tasks/Specify Data Source" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\0 Common Tasks\0 Specify Data Source.md" />
          <article name="Items Selection" sort="01 Items Selection" id="UI Widgets/UI Widget Categories/Collection Container Widgets/Common Tasks/Items Selection" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\0 Common Tasks\01 Items Selection.md" />
          <article name="Handle Item Events" sort="1 Handle Item Events" id="UI Widgets/UI Widget Categories/Collection Container Widgets/Common Tasks/Handle Item Events" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\0 Common Tasks\1 Handle Item Events.md" />
          <article name="Customize an Item Appearance" sort="2 Customize an Item Appearance" id="UI Widgets/UI Widget Categories/Collection Container Widgets/Common Tasks/Customize an Item Appearance" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\0 Common Tasks\2 Customize an Item Appearance\Customize an Item Appearance.md">
            <article name="Use a Default Item Template" sort="0 Use a Default Item Template" id="UI Widgets/UI Widget Categories/Collection Container Widgets/Common Tasks/Customize an Item Appearance/Use a Default Item Template" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\0 Common Tasks\2 Customize an Item Appearance\0 Use a Default Item Template.md" />
          </article>
          <article name="Search Through Items" sort="3 Search Through Items" id="UI Widgets/UI Widget Categories/Collection Container Widgets/Common Tasks/Search Through Items" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\0 Common Tasks\3 Search Through Items.md" />
        </article>
        <article name="List of Collection Container Widgets" sort="1 List of Collection Container Widgets" id="UI Widgets/UI Widget Categories/Collection Container Widgets/List of Collection Container Widgets" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\1 List of Collection Container Widgets\List of Collection Container Widgets.md">
          <article name="dxAccordion" sort="dxAccordion" id="UI Widgets/UI Widget Categories/Collection Container Widgets/List of Collection Container Widgets/dxAccordion" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\1 List of Collection Container Widgets\dxAccordion.md" />
          <article name="dxActionSheet" sort="dxActionSheet" id="UI Widgets/UI Widget Categories/Collection Container Widgets/List of Collection Container Widgets/dxActionSheet" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\1 List of Collection Container Widgets\dxActionSheet.md" />
          <article name="dxContextMenu" sort="dxContextMenu" id="UI Widgets/UI Widget Categories/Collection Container Widgets/List of Collection Container Widgets/dxContextMenu" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\1 List of Collection Container Widgets\dxContextMenu.md" />
          <article name="dxGallery" sort="dxGallery" id="UI Widgets/UI Widget Categories/Collection Container Widgets/List of Collection Container Widgets/dxGallery" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\1 List of Collection Container Widgets\dxGallery.md" />
          <article name="dxList" sort="dxList" id="UI Widgets/UI Widget Categories/Collection Container Widgets/List of Collection Container Widgets/dxList" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\1 List of Collection Container Widgets\dxList.md" />
          <article name="dxMenu" sort="dxMenu" id="UI Widgets/UI Widget Categories/Collection Container Widgets/List of Collection Container Widgets/dxMenu" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\1 List of Collection Container Widgets\dxMenu.md" />
          <article name="dxMultiView" sort="dxMultiView" id="UI Widgets/UI Widget Categories/Collection Container Widgets/List of Collection Container Widgets/dxMultiView" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\1 List of Collection Container Widgets\dxMultiView.md" />
          <article name="dxNavBar" sort="dxNavBar" id="UI Widgets/UI Widget Categories/Collection Container Widgets/List of Collection Container Widgets/dxNavBar" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\1 List of Collection Container Widgets\dxNavBar.md" />
          <article name="dxPanorama" sort="dxPanorama" id="UI Widgets/UI Widget Categories/Collection Container Widgets/List of Collection Container Widgets/dxPanorama" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\1 List of Collection Container Widgets\dxPanorama.md" />
          <article name="dxPivot" sort="dxPivot" id="UI Widgets/UI Widget Categories/Collection Container Widgets/List of Collection Container Widgets/dxPivot" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\1 List of Collection Container Widgets\dxPivot.md" />
          <article name="dxSlideOut" sort="dxSlideOut" id="UI Widgets/UI Widget Categories/Collection Container Widgets/List of Collection Container Widgets/dxSlideOut" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\1 List of Collection Container Widgets\dxSlideOut.md" />
          <article name="dxTabPanel" sort="dxTabPanel" id="UI Widgets/UI Widget Categories/Collection Container Widgets/List of Collection Container Widgets/dxTabPanel" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\1 List of Collection Container Widgets\dxTabPanel.md" />
          <article name="dxTabs" sort="dxTabs" id="UI Widgets/UI Widget Categories/Collection Container Widgets/List of Collection Container Widgets/dxTabs" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\1 List of Collection Container Widgets\dxTabs.md" />
          <article name="dxTagBox" sort="dxTagBox" id="UI Widgets/UI Widget Categories/Collection Container Widgets/List of Collection Container Widgets/dxTagBox" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\1 List of Collection Container Widgets\dxTagBox.md" />
          <article name="dxTileView" sort="dxTileView" id="UI Widgets/UI Widget Categories/Collection Container Widgets/List of Collection Container Widgets/dxTileView" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\1 List of Collection Container Widgets\dxTileView.md" />
          <article name="dxToolBar" sort="dxToolBar" id="UI Widgets/UI Widget Categories/Collection Container Widgets/List of Collection Container Widgets/dxToolBar" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\1 List of Collection Container Widgets\dxToolBar.md" />
          <article name="dxTreeView" sort="dxTreeView" id="UI Widgets/UI Widget Categories/Collection Container Widgets/List of Collection Container Widgets/dxTreeView" file="c:\content\10 UI Widgets\10 UI Widget Categories\10 Collection Container Widgets\1 List of Collection Container Widgets\dxTreeView.md" />
        </article>
      </article>
      <article name="Editor Widgets" sort="20 Editor Widgets" id="UI Widgets/UI Widget Categories/Editor Widgets" root="true" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\Editor Widgets.md">
        <article name="Common Tasks" sort="0 Common Tasks" id="UI Widgets/UI Widget Categories/Editor Widgets/Common Tasks" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\0 Common Tasks\Common Tasks.md">
          <article name="Get And Set a Widget Value" sort="0 Get And Set a Widget Value" id="UI Widgets/UI Widget Categories/Editor Widgets/Common Tasks/Get And Set a Widget Value" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\0 Common Tasks\0 Get And Set a Widget Value.md" />
          <article name="Handle The Value Change Event" sort="1 Handle The Value Change Event" id="UI Widgets/UI Widget Categories/Editor Widgets/Common Tasks/Handle The Value Change Event" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\0 Common Tasks\1 Handle The Value Change Event.md" />
        </article>
        <article name="Text Editors" sort="1 Text Editors" id="UI Widgets/UI Widget Categories/Editor Widgets/Text Editors" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\1 Text Editors.md" />
        <article name="List of Editor Widgets" sort="List of Editor Widgets" id="UI Widgets/UI Widget Categories/Editor Widgets/List of Editor Widgets" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\List of Editor Widgets\List of Editor Widgets.md">
          <article name="dxAutocomplete" sort="dxAutocomplete" id="UI Widgets/UI Widget Categories/Editor Widgets/List of Editor Widgets/dxAutocomplete" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\List of Editor Widgets\dxAutocomplete.md" />
          <article name="dxCalendar" sort="dxCalendar" id="UI Widgets/UI Widget Categories/Editor Widgets/List of Editor Widgets/dxCalendar" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\List of Editor Widgets\dxCalendar.md" />
          <article name="dxCheckBox" sort="dxCheckBox" id="UI Widgets/UI Widget Categories/Editor Widgets/List of Editor Widgets/dxCheckBox" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\List of Editor Widgets\dxCheckBox.md" />
          <article name="dxColorBox" sort="dxColorBox" id="UI Widgets/UI Widget Categories/Editor Widgets/List of Editor Widgets/dxColorBox" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\List of Editor Widgets\dxColorBox.md" />
          <article name="dxDateBox" sort="dxDateBox" id="UI Widgets/UI Widget Categories/Editor Widgets/List of Editor Widgets/dxDateBox" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\List of Editor Widgets\dxDateBox.md" />
          <article name="dxFileUploader" sort="dxFileUploader" id="UI Widgets/UI Widget Categories/Editor Widgets/List of Editor Widgets/dxFileUploader" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\List of Editor Widgets\dxFileUploader.md" />
          <article name="dxLookup" sort="dxLookup" id="UI Widgets/UI Widget Categories/Editor Widgets/List of Editor Widgets/dxLookup" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\List of Editor Widgets\dxLookup.md" />
          <article name="dxNumberBox" sort="dxNumberBox" id="UI Widgets/UI Widget Categories/Editor Widgets/List of Editor Widgets/dxNumberBox" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\List of Editor Widgets\dxNumberBox.md" />
          <article name="dxProgressBar" sort="dxProgressBar" id="UI Widgets/UI Widget Categories/Editor Widgets/List of Editor Widgets/dxProgressBar" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\List of Editor Widgets\dxProgressBar.md" />
          <article name="dxRadioGroup" sort="dxRadioGroup" id="UI Widgets/UI Widget Categories/Editor Widgets/List of Editor Widgets/dxRadioGroup" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\List of Editor Widgets\dxRadioGroup.md" />
          <article name="dxRangeSlider" sort="dxRangeSlider" id="UI Widgets/UI Widget Categories/Editor Widgets/List of Editor Widgets/dxRangeSlider" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\List of Editor Widgets\dxRangeSlider.md" />
          <article name="dxSelectBox" sort="dxSelectBox" id="UI Widgets/UI Widget Categories/Editor Widgets/List of Editor Widgets/dxSelectBox" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\List of Editor Widgets\dxSelectBox.md" />
          <article name="dxSlider" sort="dxSlider" id="UI Widgets/UI Widget Categories/Editor Widgets/List of Editor Widgets/dxSlider" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\List of Editor Widgets\dxSlider.md" />
          <article name="dxSwitch" sort="dxSwitch" id="UI Widgets/UI Widget Categories/Editor Widgets/List of Editor Widgets/dxSwitch" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\List of Editor Widgets\dxSwitch.md" />
          <article name="dxTagBox" sort="dxTagBox" id="UI Widgets/UI Widget Categories/Editor Widgets/List of Editor Widgets/dxTagBox" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\List of Editor Widgets\dxTagBox.md" />
          <article name="dxTextArea" sort="dxTextArea" id="UI Widgets/UI Widget Categories/Editor Widgets/List of Editor Widgets/dxTextArea" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\List of Editor Widgets\dxTextArea.md" />
          <article name="dxTextBox" sort="dxTextBox" id="UI Widgets/UI Widget Categories/Editor Widgets/List of Editor Widgets/dxTextBox" file="c:\content\10 UI Widgets\10 UI Widget Categories\20 Editor Widgets\List of Editor Widgets\dxTextBox.md" />
        </article>
      </article>
      <article name="Overlay Widgets" sort="30 Overlay Widgets" id="UI Widgets/UI Widget Categories/Overlay Widgets" root="true" file="c:\content\10 UI Widgets\10 UI Widget Categories\30 Overlay Widgets\Overlay Widgets.md">
        <article name="Common Tasks" sort="0 Common Tasks" id="UI Widgets/UI Widget Categories/Overlay Widgets/Common Tasks" file="c:\content\10 UI Widgets\10 UI Widget Categories\30 Overlay Widgets\0 Common Tasks\Common Tasks.md">
          <article name="Control The Widget Visibility" sort="0 Control The Widget Visibility" id="UI Widgets/UI Widget Categories/Overlay Widgets/Common Tasks/Control The Widget Visibility" file="c:\content\10 UI Widgets\10 UI Widget Categories\30 Overlay Widgets\0 Common Tasks\0 Control The Widget Visibility.md" />
          <article name="Specify a Widget Content" sort="05 Specify a Widget Content" id="UI Widgets/UI Widget Categories/Overlay Widgets/Common Tasks/Specify a Widget Content" file="c:\content\10 UI Widgets\10 UI Widget Categories\30 Overlay Widgets\0 Common Tasks\05 Specify a Widget Content.md" />
          <article name="Position a Widget" sort="1 Position a Widget" id="UI Widgets/UI Widget Categories/Overlay Widgets/Common Tasks/Position a Widget" file="c:\content\10 UI Widgets\10 UI Widget Categories\30 Overlay Widgets\0 Common Tasks\1 Position a Widget.md" />
          <article name="Specify a Widget Size" sort="15 Specify a Widget Size" id="UI Widgets/UI Widget Categories/Overlay Widgets/Common Tasks/Specify a Widget Size" file="c:\content\10 UI Widgets\10 UI Widget Categories\30 Overlay Widgets\0 Common Tasks\15 Specify a Widget Size.md" />
          <article name="Adjust Animation Options" sort="2 Adjust Animation Options" id="UI Widgets/UI Widget Categories/Overlay Widgets/Common Tasks/Adjust Animation Options" file="c:\content\10 UI Widgets\10 UI Widget Categories\30 Overlay Widgets\0 Common Tasks\2 Adjust Animation Options.md" />
          <article name="Display Modes" sort="3 Display Modes" id="UI Widgets/UI Widget Categories/Overlay Widgets/Common Tasks/Display Modes" file="c:\content\10 UI Widgets\10 UI Widget Categories\30 Overlay Widgets\0 Common Tasks\3 Display Modes.md" />
        </article>
        <article name="Keyboard Support" sort="1 Keyboard Support" id="UI Widgets/UI Widget Categories/Overlay Widgets/Keyboard Support" file="c:\content\10 UI Widgets\10 UI Widget Categories\30 Overlay Widgets\1 Keyboard Support.md" />
        <article name="List of Overlay Widgets" sort="2 List of Overlay Widgets" id="UI Widgets/UI Widget Categories/Overlay Widgets/List of Overlay Widgets" file="c:\content\10 UI Widgets\10 UI Widget Categories\30 Overlay Widgets\2 List of Overlay Widgets\List of Overlay Widgets.md">
          <article name="dxLoadPanel" sort="dxLoadPanel" id="UI Widgets/UI Widget Categories/Overlay Widgets/List of Overlay Widgets/dxLoadPanel" file="c:\content\10 UI Widgets\10 UI Widget Categories\30 Overlay Widgets\2 List of Overlay Widgets\dxLoadPanel.md" />
          <article name="dxLookup" sort="dxLookup" id="UI Widgets/UI Widget Categories/Overlay Widgets/List of Overlay Widgets/dxLookup" file="c:\content\10 UI Widgets\10 UI Widget Categories\30 Overlay Widgets\2 List of Overlay Widgets\dxLookup.md" />
          <article name="dxPopover" sort="dxPopover" id="UI Widgets/UI Widget Categories/Overlay Widgets/List of Overlay Widgets/dxPopover" file="c:\content\10 UI Widgets\10 UI Widget Categories\30 Overlay Widgets\2 List of Overlay Widgets\dxPopover.md" />
          <article name="dxPopup" sort="dxPopup" id="UI Widgets/UI Widget Categories/Overlay Widgets/List of Overlay Widgets/dxPopup" file="c:\content\10 UI Widgets\10 UI Widget Categories\30 Overlay Widgets\2 List of Overlay Widgets\dxPopup.md" />
          <article name="dxToast" sort="dxToast" id="UI Widgets/UI Widget Categories/Overlay Widgets/List of Overlay Widgets/dxToast" file="c:\content\10 UI Widgets\10 UI Widget Categories\30 Overlay Widgets\2 List of Overlay Widgets\dxToast.md" />
          <article name="dxTooltip" sort="dxTooltip" id="UI Widgets/UI Widget Categories/Overlay Widgets/List of Overlay Widgets/dxTooltip" file="c:\content\10 UI Widgets\10 UI Widget Categories\30 Overlay Widgets\2 List of Overlay Widgets\dxTooltip.md" />
        </article>
      </article>
      <article name="Menu Widgets" sort="40 Menu Widgets" id="UI Widgets/UI Widget Categories/Menu Widgets" root="true" file="c:\content\10 UI Widgets\10 UI Widget Categories\40 Menu Widgets\Menu Widgets.md">
        <article name="Common Tasks" sort="0 Common Tasks" id="UI Widgets/UI Widget Categories/Menu Widgets/Common Tasks" file="c:\content\10 UI Widgets\10 UI Widget Categories\40 Menu Widgets\0 Common Tasks\Common Tasks.md">
          <article name="Data Binding" sort="0 Data Binding" id="UI Widgets/UI Widget Categories/Menu Widgets/Common Tasks/Data Binding" file="c:\content\10 UI Widgets\10 UI Widget Categories\40 Menu Widgets\0 Common Tasks\0 Data Binding.md" />
          <article name="Appearance" sort="1 Appearance" id="UI Widgets/UI Widget Categories/Menu Widgets/Common Tasks/Appearance" file="c:\content\10 UI Widgets\10 UI Widget Categories\40 Menu Widgets\0 Common Tasks\1 Appearance.md" />
          <article name="Item Selection" sort="2 Item Selection" id="UI Widgets/UI Widget Categories/Menu Widgets/Common Tasks/Item Selection" file="c:\content\10 UI Widgets\10 UI Widget Categories\40 Menu Widgets\0 Common Tasks\2 Item Selection.md" />
          <article name="Handle Item Events" sort="4 Handle Item Events" id="UI Widgets/UI Widget Categories/Menu Widgets/Common Tasks/Handle Item Events" file="c:\content\10 UI Widgets\10 UI Widget Categories\40 Menu Widgets\0 Common Tasks\4 Handle Item Events.md" />
        </article>
        <article name="List of Menu Widgets" sort="1 List of Menu Widgets" id="UI Widgets/UI Widget Categories/Menu Widgets/List of Menu Widgets" file="c:\content\10 UI Widgets\10 UI Widget Categories\40 Menu Widgets\1 List of Menu Widgets\List of Menu Widgets.md">
          <article name="dxMenu" sort="10 dxMenu" id="UI Widgets/UI Widget Categories/Menu Widgets/List of Menu Widgets/dxMenu" file="c:\content\10 UI Widgets\10 UI Widget Categories\40 Menu Widgets\1 List of Menu Widgets\10 dxMenu.md" />
          <article name="dxContextMenu" sort="20 dxContextMenu" id="UI Widgets/UI Widget Categories/Menu Widgets/List of Menu Widgets/dxContextMenu" file="c:\content\10 UI Widgets\10 UI Widget Categories\40 Menu Widgets\1 List of Menu Widgets\20 dxContextMenu.md" />
        </article>
      </article>
      <article name="Layout Widgets" sort="50 Layout Widgets" id="UI Widgets/UI Widget Categories/Layout Widgets" root="true" file="c:\content\10 UI Widgets\10 UI Widget Categories\50 Layout Widgets\Layout Widgets.md">
        <article name="Specify Layout Elements" sort="0 Specify Layout Elements" id="UI Widgets/UI Widget Categories/Layout Widgets/Specify Layout Elements" file="c:\content\10 UI Widgets\10 UI Widget Categories\50 Layout Widgets\0 Specify Layout Elements.md" />